var nome = "Cristiano Soares";
var n1 = 29;
var n2 = 10;
var frase = "Cruzeiro é o melhor time do mundo";
// alert(nome + " tem " + idade + " anos");
// alert(idade + idade2);
console.log(nome);
console.log(n1 * n2);
console.log(frase.toUpperCase());
// alert(frase.replace("Cruzeiro", "CRB"));
